name: weather_app_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/graphic.png
   - assets/icons/027-humidity.png
   - assets/icons/050-barometer.png
   - assets/icons/001-wind-1.png
   - assets/icons/007-sunset.png
   - assets/icons/008-sunrise.png
   - assets/icons/sand-clock.png




  fonts:
   - family: Barlow
     fonts:
      - asset: assets/fonts/Barlow-Regular.ttf  

  
